## `docker-compose.yml`  – Dev **and** single‑node prod
# ────────────────────────────────────────────────────────────────────────────
# This file defines a single service, `api`, which runs the FastAPI app.

services:
  api:
    build: .
    env_file: backend/.env
    ports: ["8686:8686"]
    depends_on: [db, redis]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8686/health"]
      interval: 30s
      timeout: 5s
      retries: 3
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: vtproxy
      POSTGRES_USER: vtproxy
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes: [db-data:/var/lib/postgresql/data]
  redis:
    image: redis:7-alpine
    volumes: [redis-data:/data]
volumes:
  db-data: {}
  redis-data: {}
    # uncomment for live-reload in dev
    # volumes:
    #   - ./backend:/app/backend:ro

  # ─── optional reverse proxy (Traefik) ───
  # traefik:
  #   image: traefik:v3.0
  #   command:
  #     - "--api.insecure=true"
  #     - "--providers.docker=true"
  #     - "--entrypoints.web.address=:80"
  #   ports:
  #     - "80:80"
  #     - "8080:8080"   # dashboard
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro